-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Nov 07, 2014 at 07:02 PM
-- Server version: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `yii2-webservice`
--

-- --------------------------------------------------------

--
-- Table structure for table `company`
--

CREATE TABLE IF NOT EXISTS `company` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `size` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=25 ;

--
-- Dumping data for table `company`
--

INSERT INTO `company` (`id`, `name`, `description`, `size`) VALUES
(1, 'Paradigm Infotech, Inc.', 'Global brand intelligence combined with Japanese sensibility, Paradigm specializes in brand and corporate communications that can help shape the future of your business.\nParadigm is the publisher of EURObiZ Japan, the first magazine especially for European businesspeople in Japan.\n\n????????????????????????????????????????????????????????????????????????????????\n???Eurobiz Japan??????????', 'C'),
(2, 'Capital One', 'for more information: ahmed.Ennouri@tunet.tn', 'B'),
(3, 'Switch Communications', '', 'D'),
(4, 'Tekserve', 'Tekserve delivers a broad range of enterprise services, solutions, and products to support the technology needs of businesses in fields ranging from finance and retail to media and entertainment. Employing best in class products from a wide range of technology manufacturers, Tekserve helps clients by identifying, engineering, deploying, and supporting the best possible solutions for their technology challenges.\n\nFrom its famous New York City retail location in Chelsea, Tekserve stocks a wide variety of Apple products, accessories, storage solutions and display devices. Tekserve also provides system rentals, workshops and certified training, as well as the finest repair and support services. Since its inception in 1987, Tekserve has been dedicated to the service of its customers and the surrounding community.', 'E'),
(5, 'Symantec', 'Symantec helps consumers and organizations secure and manage their information-driven world. Our software and services protect against more risks at more points, more completely and efficiently, enabling confidence wherever information is used or stored.\n\nSymantec was founded in 1982 by visionary computer scientists. In that spirit, as technology changed so did Symantec. We are focused on providing security, storage and systems management solutions to help businesses and consumers secure and manage their information.', 'I'),
(6, 'TEKsystems', 'People are at the heart of every successful business initiative. At TEKsystems, we understand people. Every year we deploy over 80,000 IT professionals at 6,000 client sites across North America, Europe and Asia. Our deep insights into IT human capital management enable us to help our clients achieve their business goals - while optimizing their IT workforce strategies. We provide IT staffing solutions, IT talent management expertise and IT services to help our clients plan, build and run their critical business initiatives. Through our range of quality-focused delivery models, we meet our clients where they are, and take them where they want to go, the way they want to get there.\n\nTEKsystems. Our people make IT possible.\n\nTo network with other IT professionals and connect further with TEKsystems, join our "TEKsystems Official Network" group on LinkedIn.', 'G'),
(7, 'Axius Technologies Inc', 'Axius es una consultora de proyección internacional con foco en el asesoramiento de instituciones y empresas para el desarrollo de sus proyectos.\n\nAxius aporta tanto el análisis como la implementación de soluciones profesionales en procura del desarrollo de oportunidades de nuestros clientes, destacándose el compromiso directo de sus socios con cada tarea.\n\nCon más de 10 años de experiencia local e internacional, una vasta red de contactos y capacidad de ejecución, Axius se posiciona como una destacada alternativa en asesoramiento profesional.\n\nAxius es el vínculo ideal para búsqueda, desarrollo e implementación de nuevas oportunidades y soluciones.\n\nNuestro deseo es que aquellos que tienen un proyecto, \npiensen en nosotros como una alternativa segura', 'B'),
(8, 'Gracenote', 'If you love music and TV, chances are Gracenote plays a big role in your life. We touch hundreds of millions of people through the world’s hottest entertainment products and brands, from Spotify and iTunes to Sony and LG TVs. Our technology and data helps you identify and discover new artists, find TV shows to watch and safely connect to and enjoy all of your favorite jams on the open road.\n\nGracenote is a subsidiary of Tribune Media and has more than 800 employees in offices around the world, including Queensbury, Amsterdam, Tokyo, Munich, Berlin, Seoul, Bangalore, Taipei and San Francisco, with worldwide headquarters in Emeryville, Calif. For more information, visit www.gracenote.com.', 'F'),
(9, 'Applause', 'Formerly known as uTest, Applause is leading the app quality revolution by enabling companies to deliver digital experiences that win - from web to mobile to wearables and beyond. By combining in-the-wild testing services, software tools and analytics, Applause helps companies achieve the 360° app quality they need to thrive in the modern apps economy. Thousands of companies – including Google, Fox, Amazon, Box, Concur and Runkeeper – choose Applause to launch apps that delight their users. Learn more at www.applause.com and at http://blog.applause.com', 'D'),
(10, 'Visus LLC', '', 'B'),
(11, 'Chef', 'Vi vill göra svenskt arbetsliv bättre genom att utveckla Sveriges chefer. \n\nChef ger dig allt du behöver i din vardag som ledare. Vi är 20 personer och anordnar allt från utbildningar till evenemang samt gör Sveriges ledande magasin för chefer. Vi har funnits i 17 år och är ett av de mest framgångsrika specialförlagen. \n\nTidningen Chef når 147 000 beslutsfattare varje månad. De finns inom alla typer av organisationer/företag och branscher.', 'C'),
(12, 'DexCom', 'DexCom, Inc., a medical device company, engages in the design, development, and commercialization of continuous glucose monitoring systems for people with diabetes in the United States. The company offers FDA approved SEVEN, which includes a disposable sensor that can be inserted by a patient and used continuously for up to seven days; a transmitter; and a small handheld receiver. Its SEVEN system also received CE Mark approval for commercialization in the European Union and the countries in Asia and Latin America that recognize the CE Mark. DexCom has a collaboration agreement with Edwards Lifesciences LLC to develop products for continuously monitoring blood glucose levels in patients hospitalized for various conditions. The company was founded in 1999 and is headquartered in San Diego, California.', 'E'),
(13, 'Polyvore', 'http://www.polyvore.com/cgi/about\n\nPolyvore is a technology company pioneering a huge space: social commerce. Over 20 million unique visitors come to our site every month where they''re empowered to create, share, discover and shop, using our cutting-edge tools.\n\nWe’ve been a profitable company since 2011. We have over 90% gross margins, and our revenues are nearly tripling, year-over-year.\n\nOur business is exploding because our model turns traditional commerce on its head, allowing consumers to voice and discover what they like online. Our platform lets people mix and match products they love in unique, creative ways, while offering brands deep insight into their customers.\n\nWe’re a product and engineering-driven team of smart, creative people who work in an open, collaborative environment. Come help us build an amazing company that is disrupting commerce across industries, devices and countries.', 'D'),
(14, 'Digital Monitoring Products, Inc.', '', 'A'),
(15, 'Meetup', 'Meetup is the world''s largest network of local groups. Meetup makes it easy for anyone to organize a local group or find one of the thousands already meeting up face-to-face. More than 2,000 groups get together in local communities each day, each one with the goal of improving themselves or their communities.\n\nMeetup''s mission is to revitalize local community and help people around the world self-organize. Meetup believes that people can change their personal world, or the whole world, by organizing themselves into groups that are powerful enough to make a difference.', 'D'),
(16, 'Leidos', 'Leidos is a science and technology solutions leader working to address some of the world’s toughest challenges in national security, health, and engineering. The Company’s 22,000 employees support vital missions for our government and the commercial sector, develop innovative solutions to drive better outcomes, and defend our Nation’s digital and physical infrastructure from ‘new world’ threats. Leidos is headquartered in Reston, Va. and had approximately $6 billion in revenues for fiscal year 2013, on a pro forma basis, following the spin-off of the company’s technical, engineering and enterprise IT business on Sept. 27, 2013.', 'I'),
(17, 'Diverse Lynx', '', 'C'),
(18, 'Deloitte Digital', 'Deloitte drives progress. Our firms around the world help clients become leaders wherever they choose to compete. Deloitte invests in outstanding people of diverse talents and backgrounds and empowers them to achieve more than they could elsewhere. Our work combines advice with action and integrity. We believe that when our clients and society are stronger, so are we. \n\nDeloitte refers to one or more of Deloitte Touche Tohmatsu Limited, a UK private company limited by guarantee (“DTTL”), its network of member firms, and their related entities. DTTL and each of its member firms are legally separate and independent entities. DTTL (also referred to as “Deloitte Global”) does not provide services to clients. Please see www.deloitte.com/about for a more detailed description of DTTL and its member firms.\n\nThe content on this page contains general information only, and none of Deloitte Touche Tohmatsu Limited, its member firms, or their related entities (collectively the “Deloitte Network”) is, by means of this publication, rendering professional advice or services. Before making any decision or taking any action that may affect your finances or your business, you should consult a qualified professional adviser. No entity in the Deloitte Network shall be responsible for any loss whatsoever sustained by any person who relies on content from this page.', 'I'),
(19, 'Sony Electronics', 'Sony Corporation, headquartered out of Tokyo, Japan is primarily focused on the Electronics (such as AV/IT products & components), Game (such as PlayStation), Entertainment (such as motion pictures and music), and Financial Services (such as insurance and banking) sectors. Not only do we represent a wide range of businesses, but we remain globally unique.  Our aim is to fully leverage this uniqueness in aggressively carrying out our convergence strategy so that we can continue to emotionally touch and excite our customers. With some 900 million Sony devices in hands and homes worldwide today, a vast array of Sony movies, television shows and music, and the PlayStation Network and the Sony Entertainment Network, Sony creates and delivers more entertainment experiences to more people than anyone else on earth.\n\nThe cutting-edge co-developer of the CD, the DVD and the Blu-ray Disc format, Sony continues to break new ground with innovative products like the PlayStation®4, the PlayStation® Vita, BRAVIA® LCD televisions, VAIO® personal computers, Xperia™ smartphones and tablets, Handycam® camcorders, the F65 4K professional camera, and the Cyber-shot®, Alpha DSLR and NEX digital cameras.  In 2012, Sony led the movie, television and music industries with 21 Academy Award, 25 Golden Globe and 78 Grammy nominations. Sony has brought the world such acclaimed movies as “The Amazing Spider-Man,” “Men in Black 3” and “The Social Network” and produces hit television shows like “Breaking Bad,” “The Dr. Oz Show,” “Jeopardy!” and “Wheel of Fortune.” Sony music artists include Adele, Michael Jackson, Bruce Springsteen, Paul Simon, Usher and Kenny Chesney. And, the Sony Entertainment Network is the ultimate destination for digital music, movies, television programs and games delivered through the PlayStation Network and the Music Unlimited and Video Unlimited services.', 'I'),
(20, 'Citrix Systems', 'Citrix (NASDAQ: CTXS) is the leader in mobile workspaces, providing virtualization, networking and cloud services to enable new ways to work better. \n\nAt Citrix, we measure the value of technology by how it benefits people. It’s about what they need to do and what they need to achieve. This vision inspires us to build mobile workspace solutions that give people new ways to work better with seamless and secure access to the apps, files and services they need on any device, wherever they go.\n\nBecause in this new era, work is no longer a place – its something you do anywhere inspiration strikes. This is better for people, better for IT and better for business. Through our innovation, commitment and a compelling vision of the future of work, we’re making a difference every day at thousands of organizations in every corner of the globe. What we do at Citrix is more than a game changer; it’s a life changer.\n\nFor more information about Citrix and its talented employees, visit: http://www.citrix.com/careers\n\nSpecialties\n\nDesktop and datacenter virtualization; Cloud technologies—including virtualization, networking and orchestration; Windows application delivery; web application delivery, load-balancing, WAN optimization, SSL VPN; collaboration suites, mobility, workshifting;  Helping people work better.  Making IT departments happier by giving them back control over what really matters – delivering business-critical services, maintaining availability and limiting risk.', 'H'),
(21, 'Visionaire Partners', 'Visionaire is an architectural visualization company located in Canada that produces high quality renderings and animations of properties – residential, commercial, hospitality and more; both interior and exterior.  \n\nWhether it''s a condominium living room, or a hotel lobby, Visionaire is helping it''s clients bring their designs to life by creating artistically memorable renderings.', 'B'),
(22, 'Teradici Corporation', 'Teradici PCoIP technology is the fabric of the virtual workspace. It powers the spectrum of local, remote, mobile and collaborative workstyles, fundamentally simplifying how computing is provisioned, managed and used.\n\nTeradici PCoIP technology is deployed throughout virtual and cloud environments, in zero clients, hardware accelerators, standalone workstations and mobile devices. Simple, green, and cost-effective, the Teradici PCoIP virtual workspace architecture delivers a secure, high-definition, highly responsive computing experience.\n \nTeradici customers benefit from a broad PCoIP ecosystem of innovative products and services. Our customers include Fortune 500 enterprises and institutions around the world, local and federal government agencies, and cloud and service providers. \n\nOur commitment to innovation and development is demonstrated through our continued headcount investment and through our filing of more than 60 patent applications of which 30+ have been issued as patents to date. \n\n- Learn more about PCoIP technology - http://www.teradici.com/pcoip-technology\n- Search current job opportunities - http://www.teradici.com/careers', 'E'),
(23, 'Career Development Partners', 'eCGlobal develops consumer-based decision making solutions, combining innovative methodologies & technologies and generating rich insights, so our clients can  take better & faster decisions.', 'A'),
(24, 'West Corporation', 'Graag gezien worden om wie u bent. It’s your time to shine.\n\nBij ons bent u graag gezien. Om te praten en te discussiëren. Vertel ons wie u bent, we luisteren tot we u door en door kennen.\n\nWEST vertaalt dan uw authentieke meerwaarde voor uw klanten, van verhaal naar beeld, van krachtlijnen naar opmaak, van emoties naar foto’s, van USP naar een krachtig en creatief concept waar iedereen wat aan heeft.\n\nWEST gelooft in identiteit, authenticiteit en creativiteit en ondersteunt bedrijven en organisaties die bouwen aan een duurzame, eerlijke wereld. Omdat zij én wij winst willen maken. En omdat maatschappij en natuur geen verliezers moeten zijn.', 'B');

-- --------------------------------------------------------

--
-- Table structure for table `job`
--

CREATE TABLE IF NOT EXISTS `job` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `jobkey` varchar(255) NOT NULL,
  `jobtitle` varchar(255) DEFAULT NULL,
  `company` varchar(255) NOT NULL,
  `formattedLocationFull` text NOT NULL,
  `snippet` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=49 ;

--
-- Dumping data for table `job`
--

INSERT INTO `job` (`id`, `jobkey`, `jobtitle`, `company`, `formattedLocationFull`, `snippet`) VALUES
(1, '0bad7af498bcfe57', 'IOS Developer', 'Paradigm Infotech, Inc.', 'Illinois', 'Paradigm Infotech is seeking to recruit a self-motivated and result-driven qualified professional for the following position. Position Title: IOS Developer'),
(2, '92305d621cdb3e5b', 'Senior Director Software Engineering (AI)', 'Capital One', 'Plano, TX', 'Do you think about writing beautiful code while eating breakfast? Do you build applications you are proud of and want to tell your friends about? Do you get'),
(3, '789515470a1224a9', 'iOS Developer', 'Switch Communications', 'San Jose, CA 95131', 'Switch Communications, parent company of UberConference, is smart and we’re looking for engineers to make it smarter. Funded with $18 million from Andreessen'),
(4, 'a1fd27793d97310c', 'iOS Developer', 'Tekserve', 'New York, NY 10011', 'Tekserve is looking for an iOS Developer for a 3 week project working with our proprietary iOS applications. You must have the working experience to understand'),
(5, 'e29f806d00e9f692', 'Sr iOS Developer - Mobile', 'Symantec', 'Mountain View, CA', 'As a technical leader, you should be able to play the technical leadership role in software development life cycle You should be able to work closely with'),
(6, '5f23ce0d22a51d59', 'iOS Developer/Programmer 4/5', 'Northrop Grumman', 'Andover, MA', 'iOS Developer/Programmer 4/5 Requisition ID : 14021669 Business Sector : Information Systems Location : United States-Massachusetts-Andover US'),
(7, 'a097051e905f85cc', 'iOS Developer', 'TEKsystems', 'New York, NY', '*?4 Year Degree, BS Computer Science or Engineering *?3 - 5 years experience with developing, testing, and deploying iOS applications. *?Collaborate with'),
(8, '66829b99cf1276dd', 'iOS SDKs, Objective C, Cocoa Framework Technology Architect', 'Axius Technologies Inc', 'Beaverton, OR', 'Job Description Basic • Bachelor’s degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive'),
(9, '0db855dd03e4b38e', 'iOS Developer (Complex Apps)', 'Gracenote', 'Emeryville, CA', 'iOS Developer At Gracenote, we are passionate about powering world-class products. Our technology serves billions of requests daily to hundreds of millions of'),
(10, 'a84ab7319d5d1151', 'iOS SDKs, Objective C, Cocoa Framework Technology Architect', 'Axius Technologies Inc', 'Atlanta, GA', 'Job Description Basic • Bachelor’s degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive'),
(11, '21200c08c3e714d9', 'iOS SDKs, Objective C, Cocoa Framework Technology Architect', 'Axius Technologies Inc', 'Northbrook, IL', 'Job Description Basic • Bachelor’s degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive'),
(12, 'c9af0add889cc075', 'Designer- Mobile Games', 'Warner Bros. Entertainment Group', 'San Francisco, CA', 'SUMMARY OF POSITION Warner Bros. Games Inc. seeks a Mobile Game Designer for the Warner Bros. Games San Francisco. The position is based in San Francisco.'),
(13, 'cbe61545787a1d73', 'Mobile Developer(iOS)', 'Applause', 'Framingham, MA', 'Applause is looking for a Mobile Developer . With more than $80 million strong VC funding, the latest recently raised with a $43M round E with Goldman Sachs,'),
(14, '01d2f18649d4cac9', 'iOS Developer', 'Visus LLC', 'Santa Barbara, CA 93111', 'Job Description We are seeking a Mobile Developer iOS and Android with experience to build native mobile applications for our clients. Primary opportunities'),
(15, 'ff5f47ea59e661db', 'iOS SDKs, Objective C, Cocoa Framework Technology Architect', 'Axius Technologies Inc', 'Seattle, WA', 'Job Description Basic • Bachelor’s degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive'),
(16, 'a870eec5de550c5e', 'IOS Application Developer', 'Curexo Technologies', 'Fremont, CA 94539', 'Job Description We are searching for an iPhone/iPad Application Developer. The candidate will be responsible for maintenance, enhancement, and development of'),
(17, '078131a6702e8bab', 'iOS SDKs, Objective C, Cocoa Framework Technology Lead', 'Axius Technologies Inc', 'Beaverton, OR', 'Job Description Basic • Bachelor’s degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive'),
(18, '3b31150f8dd42e31', 'Software Development Engineer - Web', 'Chef', 'Remote', 'Our mission is to write the software that will define how an entire generation of businesses deliver technology to their customers. Our users know what is'),
(19, '24c5ef2b97febf12', 'Mobile Applications Developer', 'Timmons Group', 'Richmond, VA', 'Timmons Group is a multi-disciplined engineering and technology firm recognized nationally as a “Best Firm to Work For” by CE News. We develop solutions'),
(20, 'eec00f232ef99717', 'iOS Developer', 'Axius Technologies Inc', 'Sunnyvale, CA', 'Job Description Relevant Experience (Yrs) : At-least 3 years of industry experience with strong technical skills in developing iOS Applications Necessary'),
(21, '27e6f25b182c980f', 'Mobile Developer ios and Android', 'Consulting Professional Resources, Inc.', 'Pittsburgh, PA', 'Job Title: Mobile Developer - iOS Job Type: Full Time Location: Pittsburgh, PA Responsibilities Development of mobile applications and plugins (iOS and Android'),
(22, '6131be32d02f22bd', 'iOS SDKs, Objective C, Cocoa Framework Technology Lead', 'Axius Technologies Inc', 'Northbrook, IL', 'Job Description Basic • Bachelor’s degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive'),
(23, 'e5c1bc7dc0ed09fd', 'iOS Mobile Application Software Engineer', 'DexCom', 'San Diego, CA 92121', 'Job Description: Dexcom Inc. is currently seeking an iOS Mobile Application Software Engineer. Dexcom, Inc., headquartered in San Diego, California, is'),
(24, '6488398e702b3677', 'Software Engineer, iOS', 'Polyvore', 'Mountain View, CA', 'About Us Polyvore is a new way to discover and shop for the things you love in fashion, beauty and home decor. Polyvore disrupts the traditional e-commerce'),
(25, '945f05ae2576300e', 'iOS SDKs, Objective C, Cocoa Framework Technology Lead', 'Axius Technologies Inc', 'Seattle, WA', 'Job Description Basic • Bachelor’s degree or foreign equivalent required from an accredited institution. Will also consider three years of progressive'),
(26, '1c262d5d7a587cd6', 'Android Application Developer', 'Axius Technologies Inc', 'San Diego, CA', 'In-depth knowledge of <b>Android</b> OS and <b>Android</b> Framework a must. 4+ years of experience with <b>Android</b>. <b>Android</b> Application Development - Must demonstrate requisite...'),
(27, '62ac6ea6d8254aef', 'SOFTWARE ENGINEER - COMPUTER APPLICATIONS', 'Digital Monitoring Products, Inc.', 'Springfield, MO', 'WHY WORK FOR DMP? THE JOB We work on a wide variety of projects. If you worked here, you could work on several of these types of projects during the course...'),
(28, '6b94cd5f06acff24', 'Android Embedded Developer', 'Axius Technologies Inc', 'San Diego, CA', 'Java, JNI, <b>Android</b> programming with UI expertise, OOD principles, C++, RTOS, Socket Programming, Data Structures (Lists, Vectors, Hash maps), SQL, ADB, Device...'),
(29, '5ec19a8de5469f75', 'Sr. Android Developer', 'AutoTrader Group', 'Atlanta, GA', '<b>Android</b> Studio &amp; Gradle. Experience writing <b>Android</b> unit tests. <b>Android</b> Engineer must be able to work with minimal supervision on multiple concurrent projects...'),
(30, '3845ebb366ef6080', 'Android Developer', 'Switch Communications', 'San Jose, CA 95131', 'Create innovative applications for the Google <b>Android</b> platform. Influence every aspect of the <b>Android</b> development process from API creation to design....'),
(31, 'a981950e02702a6d', 'Android Engineer', 'Meetup', 'New York, NY', 'As the second full-time <b>Android</b> Engineer at Meetup, you’ll work across teams to build new features into our <b>Android</b> app....'),
(32, 'f1e8ffadf3750c6b', 'Android Developer', 'Switch Communications', 'San Francisco, CA 94111', 'Create innovative applications for the Google <b>Android</b> platform. Influence every aspect of the <b>Android</b> development process from API creation to design....'),
(33, 'd54c0eef2d5214fd', 'Mobile Software Developer Job', 'Leidos', 'Bethesda, MD', 'OS, <b>Android</b> or other smartphone application development environments. Mobile Software Developer (Job Number:....'),
(34, '68189b43936b33a5', 'Android Embedded Developer', 'Diverse Lynx', 'San Diego, CA', 'Java, JNI, <b>Android</b> programming with UI expertise, OOD principles, C++, RTOS, Socket Programming, Data Structures (Lists, Vectors, Hash maps), SQL, ADB, Device...'),
(35, '8f969dab389c3ad5', 'Mobile Hybrid Application Developer', 'Cognizant', 'Windsor, CT', 'Mobile Hybrid developer About Cognizant Headquartered in Teaneck, NJ and ranked among the world’s fastest growing & most admired companies, Cognizant is a...'),
(36, '1620d19c9d0ef4b0', 'Software Engineer - Full Performance', 'Professional Solutions, LLC', 'Virginia', '<b>Android</b> Mobile Device development/programming/software engineering. Demonstrated experience with <b>Android</b> SDK programming/engineering....'),
(37, '02fd8e14bdc54c4e', 'Mobile Software Engineer', 'Deloitte Digital', 'London, OH', 'OS SDK, <b>Android</b> SDK, other mobile SDKs. Mobile Software Engineers are responsible for software analysis, design, documentation, and programming to ensure...'),
(38, '2f1a8d2eefeee029', 'Web Application Developer Intern', 'Sony Electronics', 'San Diego, CA', 'Experience working on <b>Android</b> or Java development projects. Web Application Developer Intern....'),
(39, '2fd13f209404363d', 'Sr. Software Engineer, (Mobile Platform, iOS or Android)', 'Citrix Systems', 'Santa Barbara, CA', 'OS or <b>Android</b>). C++, Mobile, Platform, <b>Android</b>, i. OS or <b>Android</b>) in our Santa Barbara office. OS or <b>Android</b>) opportunity – bring your career to Citrix and let...'),
(40, '870329bd66fd0548', 'Android Developer', 'Visionaire Partners', 'Atlanta, GA', '2+ years of native <b>Android</b> development experience. Tremendous new opportunity for a Senior <b>Android</b> Programmer to join a cutting edge technology firm working on...'),
(41, 'f59c0b8d8712ed9d', 'Systems Software Engineer', 'HP', 'San Diego, CA', 'Systems Software Engineer - 1328011 Description HP is the leader in Inkjet Technology. We work to maintain this position while adding new technologies and...'),
(42, 'c4d8626c822da4de', 'Software Engineer', 'Teradici Corporation', 'Santa Clara, CA 95054', 'OS and <b>Android</b>. OS or <b>Android</b> environment; OS and <b>Android</b> mobile devices. OS or <b>Android</b> development environment and/or has what it takes to ramp up quickly....'),
(43, '96d48a7ee92e38a9', 'Associate Product Manager', 'Warner Bros. Entertainment Group', 'San Francisco, CA', 'OS, <b>Android</b> and Facebook games marketplaces, trends and best practices. SUMMARY OF POSITION....'),
(44, '0e9e8a26c2b31190', 'Embedded Software Engineer', 'Career Development Partners', 'Burlington, VT', '• 5+ years of embedded system / SoC / ASIC experience • Experience testing software and hardware products • Good software skills with C/C++ and Python'),
(45, '4ccb31123a8ca2d3', 'Mobile UI/UX Designer Developer – iOS, Android, Mobile web', 'U.S. Bank', 'Atlanta, GA', 'Mobile UI/UX Designer Developer – iOS, Android, Mobile web - 140041007 At U.S. Bank, we''re passionate about helping customers and the communities where we...'),
(46, 'e4f3b632c1bcf355', 'Principal Software Enineer - SchoolMessenger', 'West Corporation', 'Los Gatos, CA', 'OS and/or <b>Android</b> development experience with Objective-C and/or Java. OS, <b>Android</b>, J2ME, BREW, Symbian, Windows Mobile / Phone, embedded mobile apps / firmware...'),
(47, 'aabbe4fc437b5cd6', 'Senior Android Developer', 'Switch Communications', 'San Jose, CA 95131', 'Create innovative applications for the Google <b>Android</b> platform. 5+ years of experience developing with OOP and <b>Android</b> platform....'),
(48, '1c0acb876d8ba3e5', 'Mobile UI/UX Designer Developer – iOS, Android, Mobile web', 'Elavon, Inc.', 'Atlanta, GA', 'Mobile UI/UX Designer Developer – iOS, Android, Mobile web - 140041007 A leader in the payments industry, Elavon provides end-to-end payment processing...');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
